links:
  # basic(blog-frontend or backend ?)
  - name: default
    route: /
    url: http://localhost:3001
  - name: blog
    route: /blog
    url: http://site-app-server-service.default.svc.cluster.local:8080
  - name: dex
    route: /dex
    url: http://dex-app-server-service.default.svc.cluster.local:8080
  - name: recorder
    route: /recorder
    url: http://localhost:3006
  - name: tracker
    route: /tracker
    url: http://localhost:3007
  - name: redis-tcp
    route: /redis-tcp
    url: http://localhost:3005
  # static
  - name: blog-static
    route: /blog-static
    url: http://localhost:3001
  - name: dex-static
    route: /dex-static
    url: http://dex-app-server-service.default.svc.cluster.local:8080
  # api
  - name: api-blog
    route: /api-blog
    url: http://site-app-server-service.default.svc.cluster.local:8080
  - name: api-dex
    route: /api-dex
    url: http://dex-app-server-service.default.svc.cluster.local:8080
  - name: api-chat
    route: /api-chat
    url: http://chat-app-envoy-service.default.svc.cluster.local:8080
  - name: api-tracker
    route: /api-tracker
    url: http://localhost:3007
  # websocket (branch 전략 미정)
  - name: ws
    route: /ws
    url:
