import {
  type Component,
  type JSX,
  createSignal,
  onMount,
  For,
  Show,
} from 'solid-js';
import { useNavigate } from '@solidjs/router';
import { globalState } from '../constants/constants';
// image
import MantleIcon from '@public/mantle-icon.png';
// styles
import './App.css';

/**
 * Main App Component
 * New York Times inspired homepage design
 * Clean grid layout with elegant project cards
 */
const App: Component = (): JSX.Element => {
  const url = globalState.url;
  const navigate = useNavigate();

  // Navigation handlers
  const handleQuantPortfolioClick = (): void => {
    window.open('https://kyle-quant.xyz/');
  };

  const handleDevRelClick = (): void => {
    navigate('/devrel');
  };

  const handleQuantCareerClick = (): void => {
    navigate('/quant');
  };

  const handlePersonalQuantClick = (): void => {
    navigate('/personal-quant');
  };

  const handleProfileClick = (): void => {
    navigate('/profile');
  };

  const handleLinkedinClick = (): void => {
    window.open('https://www.linkedin.com/in/kyle-park-io');
  };

  const handleGithubClick = (): void => {
    window.open('https://github.com/kyle-park-io');
  };

  const handleDexClick = (): void => {
    window.open(`${url}/dex`);
  };

  const handleDoorProtocolClick = (): void => {
    window.open('https://door-protocol-frontend.vercel.app/');
  };

  const handleDistributedClick = (): void => {
    window.open(
      'https://kyle-park.notion.site/Distributed-Computing-1315e2b1051680f3bc8ee9f38bbd18a3',
    );
  };

  const handleTrackerNotionClick = (): void => {
    window.open(
      'https://kyle-park.notion.site/Token-ETH-ERC20-Tracker-Infura-API-Transfer-History-1655e2b105168058a9c4f82c00919f7b',
    );
  };

  const handleTrackerLogsClick = (): void => {
    window.open(`${url}/tracker/logs/tracker`);
  };

  const handleTimestampClick = (): void => {
    window.open(`${url}/recorder/logs/timestamp`);
  };

  const handleChainClick = (): void => {
    window.open(
      'https://kyle-park.notion.site/Chain-Communicator-08fe9b295ed34662b4a72e70a608f937',
    );
  };

  const handleJunghoClick = (): void => {
    window.open(
      'https://kyle-park.notion.site/jungho-dev-03cc176ddcdb496a969cacaeec0c253f',
    );
  };

  const handleChatClick = (): void => {
    navigate('/chat');
  };

  interface RecentPost {
    slug: string;
    title: string;
    summary: string;
    date: string;
    tags: string[];
    url: string;
  }

  const [recent, setRecent] = createSignal<RecentPost[]>([]);

  // Match the blog's own PostIndexRow/FeaturedPost: a localized ko-KR long
  // form, not the raw `YYYY-MM-DD` index.json gives us.
  const formatPostDate = (iso: string): string =>
    new Date(iso).toLocaleDateString('ko-KR', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      timeZone: 'Asia/Seoul',
    });

  onMount(() => {
    // Generated by the astro build; replaces the deleted
    // /api-blog/api/blog/sorted-by-date/top-10 endpoint.
    void fetch('/blog/index.json')
      .then((res) => (res.ok ? res.json() : []))
      .then((posts: RecentPost[]) => setRecent(posts.slice(0, 3)))
      .catch(() => setRecent([]));
  });

  return (
    <div class="home-page">
      <div class="home-container">
        {/* Featured Section */}
        <section class="home-section home-section--featured">
          <button class="featured-card" onClick={handleQuantPortfolioClick}>
            <div class="featured-card__content">
              <span class="featured-card__label">Featured</span>
              <h2 class="featured-card__title">Quant Portfolio</h2>
              <p class="featured-card__desc">
                Explore trading strategies and quantitative analysis projects
              </p>
              <span class="featured-card__link">Visit Site →</span>
            </div>
            <div class="featured-card__icon">📈</div>
          </button>
        </section>

        {/* Writing Section — recent posts, fed by the static blog build */}
        <section class="home-section">
          <div class="home-section__head">
            <h2 class="home-section__title">Writing</h2>
            <a class="home-section__more" href="/blog" rel="external">
              글 전체 보기 →
            </a>
          </div>
          <Show
            when={recent().length > 0}
            fallback={
              <a class="writing-empty" href="/blog" rel="external">
                블로그로 이동 →
              </a>
            }
          >
            <div class="writing-list">
              <For each={recent()}>
                {(post, index) => (
                  <a class="writing-item" href={post.url} rel="external">
                    <span class="writing-item__number">
                      {String(index() + 1).padStart(2, '0')}
                    </span>
                    <span class="writing-item__body">
                      <span class="writing-item__title">{post.title}</span>
                      <span class="writing-item__summary">{post.summary}</span>
                      <time class="writing-item__date" datetime={post.date}>
                        {formatPostDate(post.date)}
                      </time>
                    </span>
                  </a>
                )}
              </For>
            </div>
          </Show>
        </section>

        {/* Introduce Section */}
        <section class="home-section">
          <h2 class="home-section__title">Introduce</h2>
          <div class="home-grid home-grid--3 introduce-grid-top">
            <button
              class="project-card project-card--devrel"
              onClick={handleDevRelClick}
            >
              <img
                src={MantleIcon}
                alt="Mantle"
                class="project-card__icon-img"
              />
              <h3 class="project-card__title">DevRel</h3>
              <p class="project-card__desc">Mantle Network · Korea</p>
            </button>

            <button
              class="project-card project-card--quant"
              onClick={handleQuantCareerClick}
            >
              <span class="project-card__icon">🏦</span>
              <h3 class="project-card__title">Quant</h3>
              <p class="project-card__desc">Career</p>
            </button>

            <button
              class="project-card project-card--personal-quant"
              onClick={handlePersonalQuantClick}
            >
              <span class="project-card__icon">💰</span>
              <h3 class="project-card__title">Personal Quant</h3>
              <p class="project-card__desc">Individual trading strategies</p>
            </button>
          </div>

          <div class="home-grid home-grid--3 introduce-grid-bottom">
            <button class="project-card" onClick={handleProfileClick}>
              <span class="project-card__icon">👤</span>
              <h3 class="project-card__title">Profile</h3>
              <p class="project-card__desc">About me</p>
            </button>

            <button class="project-card" onClick={handleLinkedinClick}>
              <span class="project-card__icon">💼</span>
              <h3 class="project-card__title">LinkedIn</h3>
              <p class="project-card__desc">Professional network</p>
            </button>

            <button class="project-card" onClick={handleGithubClick}>
              <span class="project-card__icon">🐙</span>
              <h3 class="project-card__title">GitHub</h3>
              <p class="project-card__desc">Open source</p>
            </button>
          </div>
        </section>

        {/* Projects Section */}
        <section class="home-section">
          <h2 class="home-section__title">Projects</h2>
          <div class="home-grid home-grid--4">
            <button
              class="project-card project-card--dex"
              onClick={handleDexClick}
            >
              <span class="project-card__icon">💱</span>
              <h3 class="project-card__title">DEX (Uniswap V2)</h3>
              <p class="project-card__desc">Decentralized exchange</p>
            </button>

            <button
              class="project-card project-card--door"
              onClick={handleDoorProtocolClick}
            >
              <img
                src={MantleIcon}
                alt="Mantle"
                class="project-card__icon-img"
              />
              <h3 class="project-card__title">DOOR Protocol</h3>
              <p class="project-card__desc">
                Decentralized Offered Rate protocol
                <br />
                Fixed Income
                <br />
                🏆 1st Place
                <br />
                Mantle Global Hackathon 2025
              </p>
            </button>

            <button class="project-card" onClick={handleDistributedClick}>
              <span class="project-card__icon">🖥️</span>
              <h3 class="project-card__title">Distributed Computing</h3>
              <p class="project-card__desc">Parallel systems</p>
            </button>

            <button class="project-card" onClick={handleChainClick}>
              <span class="project-card__icon">🔗</span>
              <h3 class="project-card__title">Chain Communicator</h3>
              <p class="project-card__desc">Blockchain communicator</p>
            </button>

            <button class="project-card" onClick={handleJunghoClick}>
              <span class="project-card__icon">🌐</span>
              <h3 class="project-card__title">jungho.dev</h3>
              <p class="project-card__desc">Personal site infrastructure</p>
            </button>

            <button class="project-card" onClick={handleTrackerNotionClick}>
              <span class="project-card__icon">📊</span>
              <h3 class="project-card__title">Token Tracker</h3>
              <p class="project-card__desc">
                ETH/ERC20 transfer history via Infura API
              </p>
            </button>

            <button class="project-card" onClick={handleTrackerLogsClick}>
              <span class="project-card__icon">📋</span>
              <h3 class="project-card__title">Tracker Docs</h3>
              <p class="project-card__desc">Swagger API & real-time logs</p>
            </button>

            <button class="project-card" onClick={handleTimestampClick}>
              <span class="project-card__icon">⏱️</span>
              <h3 class="project-card__title">Blockchain Recorder</h3>
              <p class="project-card__desc">Block timestamp</p>
            </button>

            <button class="project-card" onClick={handleChatClick}>
              <span class="project-card__icon">💬</span>
              <h3 class="project-card__title">Chat</h3>
              <p class="project-card__desc">Anonymous real-time chat</p>
            </button>
          </div>
        </section>
      </div>
    </div>
  );
};

export default App;
